// Code generated by types_generator.go - DO NOT EDIT.

package tiledefs

const (
	_ Kind = iota
	Empty
	Water
	Grass
	Dirt
	Tree
	Bush
	VerticalWall
	HorizontalWall
	TopLeftCornerWall
	TopRightCornerWall
	BottomLeftCornerWall
	BottomRightCornerWall
	LightShade
	MediumShade
	DarkShade
	WaterSource
	HotSprings
	HealingSpot
	DangerZone
	PoisonSwamp
	Biohazard
	Radiation
	VeryWater
	Door
	Goal
)

const (
	_ Property = (1 << iota) >> 1
	Flamable
	Heals
	Hurts
	Opens
	Poison
	Walkable
)

var DefaultProperty = map[Kind]Property{
	Empty:                 0,
	Water:                 0,
	Grass:                 Walkable,
	Dirt:                  Walkable,
	Tree:                  Walkable | Flamable,
	Bush:                  Flamable,
	VerticalWall:          0,
	HorizontalWall:        0,
	TopLeftCornerWall:     0,
	TopRightCornerWall:    0,
	BottomLeftCornerWall:  0,
	BottomRightCornerWall: 0,
	LightShade:            0,
	MediumShade:           0,
	DarkShade:             0,
	WaterSource:           Heals,
	HotSprings:            Heals,
	HealingSpot:           Heals,
	DangerZone:            Hurts,
	PoisonSwamp:           Hurts | Poison,
	Biohazard:             Hurts | Poison,
	Radiation:             Hurts,
	VeryWater:             0,
	Door:                  Opens,
	Goal:                  0,
}

var SymbolToKind = map[string]Kind{
	".": Empty,
	"~": Water,
	",": Grass,
	"_": Dirt,
	"t": Tree,
	"o": Bush,
	"║": VerticalWall,
	"═": HorizontalWall,
	"╔": TopLeftCornerWall,
	"╗": TopRightCornerWall,
	"╚": BottomLeftCornerWall,
	"╝": BottomRightCornerWall,
	"░": LightShade,
	"▒": MediumShade,
	"▓": DarkShade,
	"☕": WaterSource,
	"♨": HotSprings,
	"⚕": HealingSpot,
	"⚠": DangerZone,
	"☠": PoisonSwamp,
	"☣": Biohazard,
	"☢": Radiation,
	"♒": VeryWater,
	"#": Door,
	"☆": Goal,
}
