
// Code generated by types_generator.go - DO NOT EDIT.

package somepkg

// TileType corresponds to the possible kinds of ground tiles in the
// game.  These enumerators are automatically generated from a text
// file that defines all of the possiblities.  Empty tiles are
// automatically included.
type TileType int

const (
	Empty TileType = iota
	Grass
	Dirt
	Bush
	Tree
	Water
	
)
