
// Code generated by types_generator.go - DO NOT EDIT.

package somepkg

const (
	_ Kind = iota
	Grass
	Dirt
	Bush
	Tree
	Water
	
)

const (
	_ Property = (1 << iota) >> 1
	Burns
	Nowalk
	
)

var DefaultProperty = map[Kind]Property {
	Water: Nowalk,
	Grass: Burns,
	Dirt: 0,
	Tree: Burns | Nowalk,
	Bush: Burns,

}
